### ISSUE TITLE
think over the text of the bot's messages

### ISSUE THREAD

**Issue by R4yya** [R4yya/Postgres-Monitor-Bot#12]

**Comment by Slaik1** [comment]
/start

Hello! I'm your PostgreSQL database monitoring bot.
Select a database to view metrics.
You can view all available commands in the menu.

/database меняем на /setDatabase
После выбра базы данных 
Database selected! sample_database_1
меняем на
Database sample_database_1  selected!

/metrics меняем на databaseMetrics 

/disk
Disk space:
 Free: 39.63 GB
 Total: 111.66 GB
 Usage: 64.5%

меняем на 
Usage: 72,03GB / 111.66GB (не уверен)

/cpu
*CPU information:*
 CPU usage: 24.5%

меняем на 
CPU usage 24.5%   (не уверен)
